openapi: "3.0.0"
info:
  description: "This is the documentation for the interfaces and routes to the Viral API. https://github.com/aimenhamed/SENG3011_Viral"
  version: "1.0.0"
  title: "Viral API"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "Articles"
    description: "Retrieve articles per a search criteria"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
paths:
  /articles:
    get:
      tags:
        - "Articles"
      summary: "Retrieve articles per a search criteria"
      description: "Retrieve articles based on a criteria provided in the request."
      operationId: "scrapeArticles"
      parameters:
        - in: header
          name: period_of_interest
          schema:
            $ref: "#/components/schemas/Period"
          required: true
        - in: header
          name: location
          schema:
            type: string
          required: true
        - in: header
          name: key_terms
          schema:
            type: "array"
            items:
              type: "string"
          required: true
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          "$ref": "#/components/responses/BadRequest"
components:
  responses:
    BadRequest:
      description: "This request was not formed with correct inputs"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              errorCode:
                type: "integer"
                example: 400
              errorMessage:
                type: "string"
                example: "Bad request"
  schemas:
    Location:
      type: "object"
      properties:
        country:
          type: "string"
          description: "Country of location"
        location:
          type: "string"
          description: "Location string"
        geonames_id:
          type: "number"
          description: "Optional for google api"
        google_id:
          type: "number"
          description: "Optional for google api"
      xml:
        name: "Location"
    Report:
      type: "object"
      properties:
        diseases:
          type: "array"
          items:
            type: "string"
        syndromes:
          type: "array"
          items:
            type: "string"
        eventDate:
          type: "string"
        location:
          "$ref": "#/components/schemas/Location"
    Article:
      type: "object"
      properties:
        url:
          type: "string"
        publicationDate:
          type: "string"
        headline:
          type: "string"
        mainText:
          type: "string"
        reports:
          type: "array"
          items:
            "$ref": "#/components/schemas/Report"
    Period:
      type: "object"
      properties:
        start:
          type: "string"
          description: "Start time"
        end:
          type: "string"
          description: "End time"
      xml:
        name: "Period"
    ApiRequestBody:
      type: "object"
      properties:
        period_of_interest:
          "$ref": "#/components/schemas/Period"
        key_terms:
          type: "array"
          items:
            type: "string"
        location:
          type: "string"
    ApiResponse:
      type: "object"
      properties:
        articles:
          type: "array"
          items:
            "$ref": "#/components/schemas/Article"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
